#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TaskyAndroid.Resource", IsApplication=true)]

namespace TaskyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int AddButton = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int CancelDeleteButton = 2131165192;
			
			// aapt resource value: 0x7f070003
			public const int NameLabel = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int NameText = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int NotesLabel = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int NotesText = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int SaveButton = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int TaskDetailsHeader = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int TaskList = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int lstItemTask = 2131165193;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int HomeScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskDetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskListItem = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
